title: "Michael Greifeneder"
url: "http://mikegr.github.com"
author: "Michael Greifeneder"
email: "mikegr@gmx.net"
description: "The personal blog of Michael Greifeneder."

auto: false
source: .
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
